[package]
name = "Oracle"
version = "1.0.0"
authors = []

[addresses]
oracle_addr = "_"

[dev-addresses]
oracle_addr = "0xABBA"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

