[package]
name = "bank"
version = "1.0.0"
authors = []

[addresses]
bank_addr = "_"

[dev-addresses]
bank_addr="0xCAFE"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
