[package]
name = "vault"
version = "1.0.0"
authors = []

[addresses]
vault_addr = "_"

[dev-addresses]
vault_addr = "0xCAFE"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
